version: '3.1'
services:
  mongo:
    image: mongo:6-jammy
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: ${MONGODB_DB}
    ports:
      - 27017:27017
    volumes:
      - dbdata6:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
volumes:
  dbdata6:
